# Theme
remote_theme: epidrome/cover-card@main

# Title and tag line
title: 'Politico Tech Global'
description: 'Uncertainty Simplified'

# Images
avatar: 'avatar.jpg'
background: 'clouds.jpg'
favicon: 'ptg.ico'

# Online profiles
email: 'contact@politicotechglobal.com'
download: 'github.com/politicotechglobal/politicotechglobal.github.io/raw/main/brochure/PTG%20Brochure.pdf'

social-links-order: [github-user, facebook, twitter, instagram, blog_url, email, download]

# Yaml manifest of supported social links
# Requirements:
# `name`
#     - plain-text name of the site (e.g. twitter)
#     - **mandatory**
# `url-pattern`
#     - site URL pattern containing a placeholder string (e.g. twitter.com/__USERNAME__)
#     - placeholder will be replaced by username or value specified in _config.yml (e.g. twitter.com/mytwitter)
#     - **mandatory**
# `url-scheme`
#     - the hardcoded URI/URN url-scheme (e.g. https://)
#     - can be one of: ['https://', 'http://', 'mailto:']
#     - defaults to '//'
#     - **optional**
# `icon-class`
#     - the font awesome icon class names
#     - font-awesome free and supports `fas` (solid) and `fab` (brands) styles
#     - defaults to `fab` style and uses value of `name` attribute (e.g. fab fa-2x fa-twitter)
#     - **optional**
social-links:
  - name: facebook
    url-pattern: facebook.com/__USERNAME__
    icon-class: fab fa-2x fa-facebook-f

  - name: twitter
    url-pattern: twitter.com/__USERNAME__

  - name: twitter
    url-pattern: twitter.com/__USERNAME__

  - name: linkedin
    url-pattern: linkedin.com/in/__USERNAME__

  - name: github-user
    url-pattern: github.com/__USERNAME__
    icon-class: fab fa-2x fa-github

  - name: email
    url-scheme: 'mailto:'
    url-pattern: '__USERNAME__'
    icon-class: far fa-2x fa-envelope-open

  - name: download
    url-pattern: '__USERNAME__'
    url-scheme: 'https://'
    icon-class: fas fa-2x fa-file-arrow-down
